optimisation docker

diff --git a/4.1/Dockerfile b/4.1/Dockerfile
--- a/4.1/Dockerfile
+++ b/4.1/Dockerfile
@@ -10,7 +10,7 @@ RUN set -eux; \
 	; \
 	rm -rf /var/lib/apt/lists/*;
 
-RUN set -ex; \
+RUN set -eux; \
 	\
 	savedAptMark="$(apt-mark showmanual)"; \
 	\
@@ -18,15 +18,16 @@ RUN set -ex; \
 	apt-get install -y --no-install-recommends \
 	libmcrypt-dev \
 	libfreetype6-dev \
-	libjpeg62-turbo-dev \
+	libicu-dev \
 	libjpeg-dev \
 	libmagickwand-dev \
 	libpng-dev \
+	libwebp-dev \
 	zip \
 	libzip-dev \
 	; \
 	debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)"; \
-	docker-php-ext-configure gd --with-freetype --with-jpeg; \
+	docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp; \
 	docker-php-ext-install -j$(nproc) \
 	gd \
 	exif \
@@ -50,6 +51,7 @@ RUN set -ex; \
 	| xargs -rt apt-mark manual; \
 	\
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+	rm -rf /tmp/*; \
 	rm -rf /var/lib/apt/lists/*
 
 # set recommended PHP.ini settings
@@ -59,25 +61,50 @@ RUN { \
 	echo 'opcache.interned_strings_buffer=8'; \
 	echo 'opcache.max_accelerated_files=4000'; \
 	echo 'opcache.revalidate_freq=2'; \
-	echo 'opcache.fast_shutdown=1'; \
 	echo 'opcache.enable_cli=0'; \
 	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
 
-# Active apache rewrite mode
-RUN a2enmod rewrite headers
-
 RUN { \
+	# https://www.php.net/manual/en/errorfunc.constants.php
+	echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+	echo 'display_errors = Off'; \
+	echo 'display_startup_errors = Off'; \
+	echo 'log_errors = On'; \
+	echo 'error_log = /dev/stderr'; \
+	echo 'log_errors_max_len = 1024'; \
+	echo 'ignore_repeated_errors = On'; \
+	echo 'ignore_repeated_source = Off'; \
+	echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
+
+RUN set -eux; \
+	a2enmod rewrite expires headers; \
+	{ \
 	echo 'ServerSignature Off'; \
 	echo 'ServerTokens Prod'; \
 	echo 'Header unset Composed-By'; \
 	echo 'Header unset X-Powered-By'; \
-	} > /etc/apache2/conf-enabled/spip_headers.conf
+	} > /etc/apache2/conf-enabled/spip_headers.conf; \
+	# https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html
+	a2enmod remoteip; \
+	{ \
+	echo 'RemoteIPHeader X-Forwarded-For'; \
+	# these IP ranges are reserved for "private" use and should thus *usually* be safe inside Docker
+	echo 'RemoteIPInternalProxy 10.0.0.0/8'; \
+	echo 'RemoteIPInternalProxy 172.16.0.0/12'; \
+	echo 'RemoteIPInternalProxy 192.168.0.0/16'; \
+	echo 'RemoteIPInternalProxy 169.254.0.0/16'; \
+	echo 'RemoteIPInternalProxy 127.0.0.0/8'; \
+	} > /etc/apache2/conf-available/remoteip.conf; \
+	a2enconf remoteip; \
+	# (replace all instances of "%h" with "%a" in LogFormat)
+	find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +
 
 ENV SPIP_VERSION 4.1
 ENV SPIP_PACKAGE 4.1.12
 
 # Install SPIP-Cli
-RUN set -ex; \
+RUN set -eux; \
 	cd /opt; \
 	curl --silent --show-error https://getcomposer.org/installer | php; \
 	fetchDeps=" \
@@ -101,9 +128,10 @@ RUN set -ex; \
 	chown -R www-data:www-data /usr/src/spip; \
 	\
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps; \
+	rm -rf /tmp/*; \
 	rm -rf /var/lib/apt/lists/*
 
-VOLUME ["/var/www/html"]
+VOLUME /var/www/html
 
 # SPIP
 ENV SPIP_AUTO_INSTALL 1
